= JRuby/Gradle plugins

image::https://github.com/jruby-gradle/jruby-gradle-plugin/actions/workflows/build.yml/badge.svg["Build Status", link="https://github.com/jruby-gradle/jruby-gradle-plugin/actions/workflows/build.yml"]
image::https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/jruby-gradle/jruby-gradle-plugin", title="Gitter"]

You can also join us on the link:https://groups.google.com/forum/#!forum/jruby-gradle[JRuby/Gradle mailing list]

JRuby/Gradle brings the power and flexibility of 
link:http://gradle.org[Gradle]
to the Ruby ecosystem! With JRuby/Gradle you can specify your Java and Ruby dependencies together, build jar files, run tests, and much more!.


Use of this plugin replaces the need for Rake, link:http://bundler.io[Bundler]
and link:https://github.com/jruby/warbler[Warbler].


NOTE: JRuby/Gradle 2.1 relies on JRuby 9.4 and later. +
      JRuby/Gradle 2.0 relies on JRuby 9.x and later.


This repository contains the:

* `core` (in `core-plugin/`): Rubygems proxy.
* `base` (in `base-plugin/`): dependency resolution, executing Ruby, etc.
* `jar` (in `jar-plugin/`):  packaging JRuby-based `.jar` files
* `war` (in `war-plugin/`): packaging JRuby-based `.war` files


NOTE: More documentation can be found on link:http://jruby-gradle.org[jruby-gradle.org]

NOTE: The plugins are published at link:https://plugins.gradle.org/u/rtyler[plugins.gradle.org].