== Core plugin

The core plugin is not meant for consumption by build script authors. It is rather targeted at authors of other plugins that might require some core JRuby functionality without the conventional and extensions that is associated with other JRuby-Gradle plugins.

This plugin offers the following functionality:

* A repository handler extension to resolve GEMs directly from https://rubygems.org or another GEM repository that serves the same REST API.
* Conversion between GEM-style and Ivy-style dependencies notations.
* An abstract task class (`AbstractJRubyPrepare`) for preparing local GEM + JAR installations.

== Getting Started

=== Compatibility

This plugin requires link:http://gradle.org[Gradle] 4.3 or better

=== Installing

.build.gradle
[source, groovy]
----
plugins {
  id 'com.github.jruby-gradle.core' version 'VERSION-OF-PLUGIN'
}
----

=== Adding repositories

.build.gradle
[source,groovy]
----
repositories {
    ruby.mavengems() // <1>
    ruby.mavengems('https://foo.bar') // <2>
    ruby.mavengems('https://foo.bar', 'acme-rubygems') // <3>
}
----
<1> Adds a Maven repository that uses the one official supported by the JRuby group. In order to use this, GEM dependencies should all be placed in the `rubygems` group.
<2> Adds a custom Maven repository that will proxy a GEMs repository. In order to use this, GEM dependencies should all be placed in the `rubygems` group.
<3> Adds a custom Maven repository that will proxy a GEMs repository, but allocate a custom dedicated Maven group. This is useful where you would want to use both the public repository and your own, but you want to save network query traffic, by only query repositories where you know the dependencies should exist.